### ISSUE TITLE
Move, Embed, Link to Linux installation instructions in installation section.

### ISSUE THREAD

**Issue by freylint** [R2Northstar/NorthstarWiki#102]
I suggest adding a link/ embed of the Linux installation instructions at `Using Northstar/Playing on Linux` to the `Installing Northstar/Basic Setup` as I assumed, as a Linux user, that there would be no meaningful support for linux in the automatic installers (there is).
I then went straight to manual and found no reference to Linux installation, so I then assumed the project had no support for linux and spent a few hours  playing around with custom wine prefixes to get Northstar working.

This might just be a me thing, but a simple change like this might save who are accustomed to getting no Linux support some time. Especially if you're going to go through the effort to support Linux.

**Comment by itscynxx** [comment]
i would say this is resovled 
![image](https://github.com/R2Northstar/NorthstarWiki/assets/70904206/e1b1c6a5-3935-4a33-9a2f-f897b1d52120)

**Comment by GeckoEidechse** [comment]
Additionally there's also a top level entry in the sidebar so I'm marking this as resolved.

![image](https://github.com/R2Northstar/NorthstarWiki/assets/40122905/e707632f-e912-4c09-ab92-62e470acd7ca)

**Comment by GeckoEidechse** [comment]
@freylint if you have any more feedback on this matter, please let me know and/or re-open the issue <3
