### ISSUE TITLE
Something about `msvcr120`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#107]
By @james-amarth

> It seems to be that `msvcr120` isn't actually installed with Titanfall, despite being required (also not present in `__Installer`), could we get a troubleshooting page about it with the fix being to install https://aka.ms/highdpimfc2013x64enu 
> VS2013 correlates to msvcr120 (instead of 2012 being 120, thanks Microsoft)
> it's cropped up a few times as of recent and probably more with the steam sale making Titanfall cheap

**Comment by GeckoEidechse** [comment]
Note that it's not clear yet whether simply starting vanilla first would solve the issue.

**Comment by pg9182** [comment]
You do need msvcr120, but it does often come with many other games.

**Comment by GeckoEidechse** [comment]
Having recently performed a fresh install and experienced the error myself I can confirm that starting vanilla does not fix it.

Either way instructions on how to resolve where added with #116 so this issue can be closed now ^^
