### ISSUE TITLE
Document master server functionality

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#14]
As the master server currently is a single point of failure in the Northstar ecosystem, improving its stability and implementing alternative versions should help ensure availability of the project in the long-term.

As such documenting functionality of the master server is vital to reduce the barrier of contributing to it.

Any help on that endeavour is more than welcome <3

**Comment by SebiiB** [comment]
Clicking "Launch Northstar" does nothing for about a minute, then pops up with an authentication failed error on 1/10

**Comment by GeckoEidechse** [comment]
> Clicking "Launch Northstar" does nothing for about a minute, then pops up with an authentication failed error on 1/10

This is unrelated to this thread and is due to an outage with the master server. Please check the announcements channel in the [Northstar Discord server](https://discord.gg/northstar) for more information.

**Comment by GeckoEidechse** [comment]
Done with #42
