### ISSUE TITLE
Update descriptions of `-vanilla`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#258]
Required once

- https://github.com/R2Northstar/NorthstarLauncher/pull/601

is merged.

**Comment by GeckoEidechse** [comment]
cc @ASpoonPlaysGames (PR author) and @itscynxx (wiki PR goat <3)

**Comment by ASpoonPlaysGames** [comment]
https://github.com/R2Northstar/NorthstarWiki/blob/32e2a2aeb55db63ccf6cb29ac648d79872670804/docs/installing-northstar/troubleshooting.md?plain=1#L131

https://github.com/R2Northstar/NorthstarWiki/blob/32e2a2aeb55db63ccf6cb29ac648d79872670804/docs/using-northstar/launch-arguments.md?plain=1#L8

https://github.com/R2Northstar/NorthstarWiki/blob/32e2a2aeb55db63ccf6cb29ac648d79872670804/docs/installing-northstar/troubleshooting.md?plain=1#L134

These are the only mentions of `-vanilla`

**Comment by itscynxx** [comment]
Currently heading towards Thanksgiving dinner; if spoon doesn't want to do it, I'll do it in 6-8 hours maybe

Also, thanks for finding the current mentions of -vanilla spoon

would write a better comment but github mobile
