### ISSUE TITLE
no list of weapons

### ISSUE THREAD

**Issue by Fabled-Sable-Girl** [R2Northstar/NorthstarWiki#26]
when clicking on the link in `ns_disallowed_weapons` and `ns_disallowed_weapon_primary_replacement`
on Hosting a Dedicated Server causes the page to reload at the top
i don't see a list of weapons

**Comment by abarichello** [comment]
Added in https://github.com/R2Northstar/NorthstarWiki/commit/6c03b4dc21e29012bcf9a872d9ca155dceb41e49
