### ISSUE TITLE
Northstar on Windows 7

### ISSUE THREAD

**Issue by Klemmbaustein** [R2Northstar/NorthstarWiki#261]
According to *@deleteduser1c3a7428* on Discord, this is a way of running Northstar on Windows 7:
> When you launch Northstar in version 1.21.0 on Windows 7, an error appears:
> CreateFile2 didn't exist on KERNEL32.DLL
> 
> When you launch Northstar as I said an error appears:
>
> ```
> One dependency code missing
> ---------------------------
> NorthstarLauncher.exe
> ---------------------------
> CreateFile2 missing in KERNEL32.dll. 
> ---------------------------
> ```
>
> And that one is easy to fix and keep playing using windows 7 
>
> Need to open Northstar.dll with CFF Explorer and go into Import Directory then click on KERNEL32.DLL and scroll down until you find `CreateFile2` and change it to `CreateFileA` and save the Northstar.dll

Maybe we should add this info to the Wiki in some way?

**Comment by pg9182** [comment]
Are we properly setting the winapi version during build?

Edit: Yeah, looks like we aren't setting it. We need to define `_WIN32_WINNT`.

**Comment by itscynxx** [comment]
> Are we properly setting the winapi version during build?
> 
> Edit: Yeah, looks like we aren't setting it. We need to define `_WIN32_WINNT`.

So should this be related back to a pr in launcher instead, or should this workaround be added to the wiki regardless?

**Comment by EM4Volts** [comment]
im against this in a hard hard way.
windows 7 has ben end of life for over 3 years, with no security updates.
we should not give people that still run it for whatever reason (ms gave enough free updates to win10 and 11 over the years) real support.

people still running win 7 should just update their OS
steam, the main platform users play the game with no longer supports windows 7 either and if they ever have issues with steam people will also fall back to this place.

**Comment by GeckoEidechse** [comment]
This has been addressed with https://github.com/R2Northstar/NorthstarLauncher/pull/770 and also per https://github.com/R2Northstar/NorthstarLauncher/discussions/668#discussioncomment-8446546 we don't support Windows 7 anyways.
