### ISSUE TITLE
Thunderstore Documentation

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#40]
Northstar is transitioning to [Thunderstore](https://northstar.thunderstore.io/) as the main place for sharing and downloading mods. As such we need documentation for

- [Using Northstar section](https://r2northstar.gitbook.io/r2northstar-wiki/using-northstar/mods)
  - How to download mods and install them
  - Anything to look out for (mod manager still broken atm for example)
  - Maybe mention current mod managers if any support Thunderstore already?
- Modding section:
  - How to upload mods
  - How to ensure mods fit the requirements posed by Thunderstore
  - Should include links to:
    - https://northstar.thunderstore.io/package/create/docs/
    - https://github.com/laundmo/northstar-mod-template

**Comment by BigSpice** [comment]
^
bump

**Comment by GeckoEidechse** [comment]
Closed for the most part with #43
