### ISSUE TITLE
Broken links on wiki

### ISSUE THREAD

**Issue by dilirity** [R2Northstar/NorthstarWiki#66]
https://r2northstar.gitbook.io/r2northstar-wiki/modding-and-development/development
- Northstar link

https://r2northstar.gitbook.io/r2northstar-wiki/contributing
- Development link

https://r2northstar.gitbook.io/r2northstar-wiki/modding-and-development/development/northstarmasterserver
- direct connect link
- normal server link

**Comment by GeckoEidechse** [comment]
Hmm, re-opening cause 

> https://r2northstar.gitbook.io/r2northstar-wiki/contributing
> - Development link

is still broken. Seems to be more than a sync issue as mentioned in #67

**Comment by dilirity** [comment]
@GeckoEidechse that's weird. I deployed it on an unlisted gitbook for testing, and it's working - https://dilirity.gitbook.io/untitled/contributing.

**Comment by GeckoEidechse** [comment]
> Hmm, re-opening cause
> 
> > https://r2northstar.gitbook.io/r2northstar-wiki/contributing
> > 
> > * Development link
> 
> is still broken. Seems to be more than a sync issue as mentioned in #67

Fixed with b772a1fc6b0da0bbc87b9e128880c2c431e1b059
