### ISSUE TITLE
Conflicting info on live fire

### ISSUE THREAD

**Issue by CTalvio** [R2Northstar/NorthstarWiki#69]
To launch a server for Live Fire, gamemode needs to be set to "speedball", not "lf". If "lf" is used, the server starts up with Skirmish.

Simultaneously, for a server to display as Live Fire in the server browser, "lf" _does_ need to be set, but only as the playlist.

Nowhere did I find this info on the wiki hosting info page, and the "speedball" term I only found on discord.

**Comment by GeckoEidechse** [comment]
Huh, thanks for the heads-up <3

**Comment by BobTheBob9** [comment]
this is a vanilla issue, the gamemode is speedball, and the playlist is lf, it's the only playlist/gamemode in the game to be like this (thanks respawn!)

**Comment by CTalvio** [comment]
Right, want it to be documented, as the wiki currently does not make note of this.

I was left scratching my head on why my Live Fire server kept starting up with skirmish, yet "correctly" appearing as Live Fire in the server browser. I found the "speedball" term on discord, but there "lf" was missing a mention in turn.

In both cases, setting up a server, one will run into this "special case" causing confusing issues. Both terms need to be included in the wiki, then, along with an explanation.

**Comment by GeckoEidechse** [comment]
I'm not quite sure what the best place is to mention that for Live Fire gamemode and playlist variable are different. A disclaimer in _[Gamemodes](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/dedicated-server#gamemodes)_ section on the _[Hosting a Dedicated Server](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/dedicated-server)_ page maybe?

**Comment by CTalvio** [comment]
Gamemodes section, I'd say. That's the list I suspect people setting up servers will most often check.

Maybe add a third column called Gamemode next to playlist. Either add a third column for whole the table, with the same names for playlist and gamemode for all but Live Fire, or move Live Fire into it's own table either above or below of the other vanilla modes.

| Playlist | Gamemode | Title |
| --- | --- | --- |
| lf | speedball | Live Fire |

Perhaps also mention in the blurb at the top of the section, that Live Fire is an exception to the rule, where playlist and gamemode names for it differ, and that startup args need to be set accordingly. Or better yet, have it in a table of it's own, with the disclaimer right next to it.

**Comment by GeckoEidechse** [comment]
Closed by #74
