### ISSUE TITLE
Broken link in hosting-a-server-with-northstar/prerequisites.md

### ISSUE THREAD

**Issue by updateing** [R2Northstar/NorthstarWiki#7]
The `[the instruction for setting up Northstar for PUGs](Northstar-PUGs-Setup/)` link in the last paragraph is broken. And this file does not seem to exist at all. Maybe someone forget to git add?

Here is the [source](https://github.com/R2Northstar/NorthstarWiki/blob/main/docs/hosting-a-server-with-northstar/prerequisites.md?plain=1#L48). I've copied the paragraph below for a quicker peek.

>## Extras:
>
>Northstar uses a config file to set various settings for your custom server. The file is located at `Titanfall2\R2Northstar\mods\Northstar.CustomServers\mod\cfg\autoexec_ns_server.cfg`
>
>In particular:
>
>* `ns_server_name` sets the name of your server on the server browser. You probably want to change this to something the people you play with recognise.
>* `ns_auth_allow_insecure` decides whether to allow players not authenticated with Northstar master server. Change the value from `0` to `1` if you want to play with vanilla clients. To find out what else you need to do for vanilla clients to join, read [the instruction for setting up Northstar for PUGs](Northstar-PUGs-Setup/).

**Comment by GeckoEidechse** [comment]
Thanks for the heads-up ^^

The link is a leftover from importing stuff [from my old wiki](https://gitlab.com/GeckoEidechse/northstar-docs-wip/-/wikis/Northstar-PUGs-Setup). Basically explains how to get vanilla clients to join a Northstar server as it was made before the public release of Northstar.

With the public release that guide is now obsolete, so I'll just remove that section as it also contains duplicate content of the [next page](https://r2northstar.gitbook.io/r2northstar-wiki/hosting-a-server-with-northstar/basic-listen-server).

If enough interest exists though, I can add a section on how to get vanilla clients to join a Northstar server.
