### ISSUE TITLE
Rewrite installation pages to mention auto-installers as the recommended installation method

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/NorthstarWiki#72]
We're making r2modman, Viper, and VTOL the recommended way of installing Northstar over manual installation.

This change affects the main installation page as well as pages for other platforms like Linux and SteamDeck, and pages reference installation.

**Comment by itscynxx** [comment]
i would say this is resolved 
![image](https://github.com/R2Northstar/NorthstarWiki/assets/70904206/d31ae533-e261-4536-840e-168d9a482fd5)

**Comment by GeckoEidechse** [comment]
Good catch. Closing for now ^^
