### ISSUE TITLE
+setplaylistvaroverride "custom_air_accel_pilot [value]" does not work

### ISSUE THREAD

**Issue by juwe-de** [R2Northstar/NorthstarWiki#9]
Hi,
Me and my friend are trying to configue a server. Unfortunately it doesn't quite work the way it is supposed to work. We are trying to override the "custom_air_accel_pilot" variable based of of [this](https://www.youtube.com/watch?v=EZ3w2Nl9SZo) video. As I said, this is not working, the variable is still the same. We couldn't find any other documentation on this page, Youtube or any other website. Any help would be appreciated

**Comment by BulletMemes** [comment]
The command is actually `+setplaylistvaroverrides "custom_air_accel_pilot [value]"`

You forgot to add a s at the end of override.

**Comment by GeckoEidechse** [comment]
> You forgot to add a s at the end of override.

Yeah, that's on me. I had a typo in the command on the wiki :c
